import React, { useContext, useEffect, useState } from 'react'
import Loader from '../components/custom/Loader'
import RenderImages from '../components/custom/RenderImages'
import { motion } from "motion/react"
import { toast } from 'react-toastify'
import axios from 'axios'
import AppContext from '../contexts/AppContext/AppContext.js'

const CommunityPostsPage = () => {

  const [loading, setLoading] = useState(false);
  const [communityImages, setCommunityImages] = useState([]);
  const [searchedImages, setSearchedImages] = useState([]);
  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);

  const { backendUrl } = useContext(AppContext);

  const handleSearch = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResults = communityImages.filter((image) =>
          image.authorName.toLowerCase().includes(searchText.toLowerCase()) ||
          image.prompt.toLowerCase().includes(searchText.toLowerCase())
        );

        setSearchedImages(searchResults);
      }, 500)
    );
  }

  useEffect(() => {
    const fetchImages = async () => {
      setLoading(true);
      try {
        const { data } = await axios.get(`${backendUrl}/api/image/get-community-images`);
        if (data.success) {
          setCommunityImages(data.images.reverse());
        } else {
          toast.error(data.message);
        }
      } catch (error) {
        toast.error(error.message);
      }
      setLoading(false);
    }

    fetchImages();
  }, []);

  return (
    <motion.section
      initial={{ opacity: 0.2, y: 100 }}
      transition={{ duration: 1 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className='min-h-[80vh] text-center pt-10 mb-10 md:mx-20'>
      <h1 className='text-center text-3xl font-medium mb-3'>The Community Showcase</h1>
      <p className='text-base text-zinc-500 mb-6 sm:mb-10'>Browse through a collection of imaginative & visually stunning images generated by PixAI.</p>

      <div className='flex items-center justify-center gap-5'>
        <div className='bg-neutral-500 flex-1 px-4 py-2.5 rounded-md mb-5 focus-within:ring-2 focus-within:ring-stone-950 transition duration-150'>
          <input onChange={handleSearch} type="text" name="searchImages" id="search-images" value={searchText} placeholder='Search Images' className='bg-transparent outline-none w-full placeholder:text-[#e0e0e087] text-[#e0e0e0]' />
        </div>
      </div>

      <div className='mt-5'>
        {loading ?
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
          :
          <div>
            {searchText &&
              <h2 className='text-xl mb-12'>
                Showing results for "<span className='font-semibold'>{searchText}</span>"
              </h2>
            }
            <div className='grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 gap-4'>
              {searchText ?
                <RenderImages images={searchedImages} title="No search results found" />
                :
                <RenderImages images={communityImages} title="No posts found" />
              }
            </div>
          </div>
        }
      </div>

    </motion.section>
  )
}

export default CommunityPostsPage